### ISSUE TITLE
Notice a strange error on premade builds including itty.bitty.site

### ISSUE THREAD

**Issue by DigiMancer3D** [alcor/itty-bitty#72]
So I've been getting this error, "Error: TypeError: Cannot read properties of undefined (reading 'code')" on older builds using ittybitty but today even the main site https://itty.bitty.site is getting this error.

![Screenshot 2022-06-05 133236](https://user-images.githubusercontent.com/18541488/172065328-28d55200-c7d4-4c8b-b1b1-8b751ea5c1ab.png)

**Comment by alcor** [comment]
This should be resolved, please check ? :‌)

**Comment by DigiMancer3D** [comment]
Still seeing this in some situations like private browsers & embedding but yes it does see to have been fixed for most builds. Thank you for the update. FYI: the main IB site is still outputting this error.
